#cloud-config
package_update: true
package_upgrade: false

packages:
  - git
  - make
  - tmux
  - jq
  - ripgrep
  - moreutils
  - chromium
  - fonts-liberation
  - pandoc
  - golang-go
  - bind9-dnsutils
  - massdns
  - seclists
  - pv
  - parallel
  - libpcap-dev
  - pkg-config

write_files:
  - path: /etc/profile.d/go.sh
    permissions: '0644'
    content: |
      export GOPATH=/root/go
      export PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"

  - path: /root/bootstrap.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -euxo pipefail
      export GOPATH=/root/go
      export PATH="$GOPATH/bin:/root/.local/bin:/usr/local/go/bin:$PATH"

      # Workspace
      mkdir -p /root/recon
      cd /root/recon
      if [ ! -d live ]; then
        # Replace with your own repo if needed
        git clone --depth 1 https://github.com/CBergane/recon.git live || mkdir -p live
      fi

      cd /root/recon/live
      # If user-data attached files exist, use them
      [ -f /tmp/recon.sh ] && cp /tmp/recon.sh ./recon.sh && chmod +x ./recon.sh || true
      [ -f /tmp/Makefile ] && cp /tmp/Makefile ./Makefile || true
      [ -f /tmp/resolvers.txt ] && mkdir -p input && cp /tmp/resolvers.txt input/resolvers.txt || true
      [ -f /tmp/resolvers-trusted.txt ] && mkdir -p input && cp /tmp/resolvers-trusted.txt input/resolvers-trusted.txt || true

      make install
      make prepare

  - path: /root/tmux_recon.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -Eeuo pipefail
      SESSION="recon"
      BASE="/root/recon/live"
      mkdir -p "$BASE"
      cd "$BASE"

      # Create or attach to session
      if ! tmux has-session -t "$SESSION" 2>/dev/null; then
        tmux new-session -d -s "$SESSION" -n run

        # Window 0: run (ready to execute)
        tmux send-keys -t "$SESSION:0" 'cd /root/recon/live && clear && echo "[run] make run PROFILE=${PROFILE:-vps}"' C-m

        # Window 1: logs (follow log)
        tmux new-window -t "$SESSION" -n logs
        tmux send-keys -t "$SESSION:1" 'cd /root/recon/live && mkdir -p out && ln -sfn "$(pwd)/out/latest" out.latest || true && clear && echo "[logs] tail -F out.latest/run.log" && tail -F out.latest/run.log' C-m

        # Window 2: watch (overview)
        tmux new-window -t "$SESSION" -n watch
        tmux send-keys -t "$SESSION:2" 'cd /root/recon/live && watch -n 5 '\''ls -lh out.latest; echo; sed -n "1,20p" out.latest/report.md 2>/dev/null; echo; tail -n 30 out.latest/run.log'\''' C-m
      fi

      # Auto-run control: touch /root/recon/.autorun to auto start
      if [ -f /root/recon/.autorun ]; then
        tmux send-keys -t "$SESSION:0" 'make run PROFILE=vps' C-m
      fi

runcmd:
  - [ bash, -lc, "/root/bootstrap.sh" ]
  - [ bash, -lc, "/root/tmux_recon.sh" ]

final_message: "cloud-init complete on $(hostname) at $(date) — tmux session 'recon' created"